openapi: 3.0.3
info:
  title: 'Credit System Api'
  description: 'Version: 1.0.0'
  version: 1.0.0
servers:
  -
    url: api.credit-api.test
paths:
  /deposits:
    get:
      summary: 'Get deposit list'
      description: 'This endpoint lets you get deposit list.'
      parameters:
        -
          in: query
          name: uuid
          description: 'The Merchant UUID.'
          example: 224d4a1f-6fc5-4039-bd81-fcbc7f88c659
          required: true
          schema:
            type: string
            description: 'The Merchant UUID.'
            example: 224d4a1f-6fc5-4039-bd81-fcbc7f88c659
        -
          in: query
          name: sign
          description: Signature.
          example: e38c3a02a3d9757c912d0dc6240a5c88
          required: true
          schema:
            type: string
            description: Signature.
            example: e38c3a02a3d9757c912d0dc6240a5c88
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: 'empty record'
          content:
            application/json:
              schema:
                type: object
                example:
                  data: []
                  meta:
                    pagination:
                      total: 0
                      count: 0
                      per_page: 10
                      current_page: 1
                      total_pages: 1
                      links: {  }
                      sortBy: id
                      descending: false
                properties:
                  data:
                    type: array
                    example: []
                  meta:
                    type: object
                    example:
                      pagination:
                        total: 0
                        count: 0
                        per_page: 10
                        current_page: 1
                        total_pages: 1
                        links: {  }
                        sortBy: id
                        descending: false
      tags:
        - 'Deposit API'
    post:
      summary: 'Create a deposit'
      description: 'This endpoint lets you create a deposit.'
      parameters:
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    name: 'Test Merchant'
                    order_id: YIHT1@PfHXEEVIqt
                    merchant_order_id: '9798223690986'
                    amount: '1000.0000'
                    status: 2
                    callback_url: jenkins.com/quia
                properties:
                  data:
                    type: object
                    example:
                      name: 'Test Merchant'
                      order_id: YIHT1@PfHXEEVIqt
                      merchant_order_id: '9798223690986'
                      amount: '1000.0000'
                      status: 2
                      callback_url: jenkins.com/quia
        422:
          description: 'parameter error'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'The merchant order id has already been taken.'
                  errors:
                    merchant_order_id:
                      - 'The merchant order id has already been taken.'
                properties:
                  message:
                    type: string
                    example: 'The merchant order id has already been taken.'
                  errors:
                    type: object
                    example:
                      merchant_order_id:
                        - 'The merchant order id has already been taken.'
      tags:
        - 'Deposit API'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_order_id:
                  type: string
                  description: 'The order id created by merchant.'
                  example: '9798223690986'
                currency:
                  type: string
                  description: 'The currency of the deposit.'
                  example: VND
                channel:
                  type: string
                  description: 'Payment Channel of the deposit.'
                  example: MOMOPAY
                method:
                  type: string
                  description: 'Payment method supported by selected Payment channel.'
                  example: TEXT
                uuid:
                  type: string
                  description: 'The Merchant UUID.'
                  example: 224d4a1f-6fc5-4039-bd81-fcbc7f88c659
                sign:
                  type: string
                  description: Signature.
                  example: d72b7a2c1fda1b4914354e6c5dbb0038
                amount:
                  type: string
                  description: 'Amount of the deposit.'
                  example: '1000'
                callback_url:
                  type: url
                  description: "Callback URL of the deposit,\nif not set, it would be the setting in merchant panel."
                  example: 'http://callback.url/0001'
              required:
                - merchant_order_id
                - currency
                - channel
                - method
                - uuid
                - sign
                - amount
  '/deposits/{id}':
    get:
      summary: 'Get a deposit'
      description: 'This endpoint lets you get a deposit.'
      parameters:
        -
          in: query
          name: uuid
          description: 'The Merchant UUID.'
          example: 224d4a1f-6fc5-4039-bd81-fcbc7f88c659
          required: true
          schema:
            type: string
            description: 'The Merchant UUID.'
            example: 224d4a1f-6fc5-4039-bd81-fcbc7f88c659
        -
          in: query
          name: sign
          description: Signature.
          example: e38c3a02a3d9757c912d0dc6240a5c88
          required: true
          schema:
            type: string
            description: Signature.
            example: e38c3a02a3d9757c912d0dc6240a5c88
        -
          in: header
          name: Api-Version
          description: ''
          example: v1
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    name: 'Test Merchant'
                    order_id: YIHT1@PfHXEEVIqt
                    merchant_order_id: '9798223690986'
                    amount: '1000.0000'
                    status: 2
                    callback_url: jenkins.com/quia
                properties:
                  data:
                    type: object
                    example:
                      name: 'Test Merchant'
                      order_id: YIHT1@PfHXEEVIqt
                      merchant_order_id: '9798223690986'
                      amount: '1000.0000'
                      status: 2
                      callback_url: jenkins.com/quia
        404:
          description: 'not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\MerchantDeposit].'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\MerchantDeposit].'
      tags:
        - 'Deposit API'
    parameters:
      -
        in: path
        name: id
        description: 'The Merchant Order ID of the deposit.'
        example: '9798223690986'
        required: true
        schema:
          type: string
tags:
  -
    name: 'Deposit API'
    description: "\nBefore using API, make sure you have an merchant acount."
components:
  securitySchemes:
    default: []
security:
  -
    default: []
